version: '3'

services:
  quotes_postgres:
    image: postgres
    container_name: tv-quotes-api-postgres
    hostname: tv-quotes-api-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: postgres

  quotes_api:
    container_name: tv-quotes-api
    hostname: tv-quotes-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:secretPassword@tv-quotes-api-postgres:5432/postgres
