services:
  database:
    image: postgres
    container_name: tv-quotes-api-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: postgres

  api:
    container_name: tv-quotes-api
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:secretPassword@tv-quotes-api-postgres:5432/postgres

networks:
  default:
    name: nginx
    external: true
